#!/bin/bash

browser=elinks
site=www.google.ie

# Concat all the command line args together into the search string
for word in $*
do
        word=${word// /+}
        word=${word//\"/%22}
	if [ "$query" ]; then
		# This is word 2 - word n
		query="$query+$word"
	else
		# This is the first word
		query=$word
	fi
done

if [ "$query" ]; then
	# A query string has been constructed
	$browser $site/search?q=$query
else
	# No query string was provided
	$browser $site
fi
